name: Test React Application


on:
  pull_request:
    branches: [ development ]
  workflow_dispatch:
jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run ESLint
        uses: yarn lint