name: Test React Application
on:
  pull_request:
    branches: [ development ]
  workflow_dispatch:
defaults:
  run:
    working-directory: ./
jobs:
  static_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: npm i
      - name: Run ESLint
        run: npm run lint
      - name: Run Tests
        run: npm run test